#!/usr/bin/env python3
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"
_CODE_DIRS = [_PROGRAM_DIR / "piper_recording_studio", _PROGRAM_DIR / "export_dataset"]

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
subprocess.check_call([context.env_exe, "-m", "black", "--check"] + [str(d) for d in _CODE_DIRS])
subprocess.check_call([context.env_exe, "-m", "isort", "--check"] + [str(d) for d in _CODE_DIRS])
subprocess.check_call([context.env_exe, "-m", "flake8"] + [str(d) for d in _CODE_DIRS])
subprocess.check_call([context.env_exe, "-m", "pylint"]  + [str(d) for d in _CODE_DIRS])
subprocess.check_call([context.env_exe, "-m", "mypy"]  + [str(d) for d in _CODE_DIRS])
